export interface ChannelModel {

    id: number,
    user: {
      pk: number,
      username: string,
      full_name: string,
      is_private: boolean,
      profile_pic_url: 'https://lh5.googleusercontent.com/proxy/oNavVqUIOD6wsH_yDlZNWCzKPh5dfY2yHt5HYquTT5HSQDg0Epr3J9sZaxgVT7nkPmF6_BGugtsMPIDtu_QRrIx5JEQANWCIpy-X5nPe01F0uMMwFv7jfNXEpmXgY1S9YeE=s0-d' ,
      
      profile_pic_id: string,
      is_verified: boolean,
      has_anonymous_profile_picture: boolean,
      media_count: number,
      follower_count: number,
      following_count: number,
      following_tag_count: number,
      biography: string,
      can_link_entities_in_bio: boolean,
      biography_with_entities: {
        raw_text: string,
        entities: any,
      },
      biography_product_mentions: any,
      external_url: 'https://linklist.bio/gcaraciolo',
      external_lynx_url:
        'https://l.instagram.com/?u=https%3A%2F%2Flinklist.bio%2Fgcaraciolo&e=ATM2DScQJjkGsQAR5V3AFV1NCmhYSScU_24-TZ4g4ci8OkecBKVvQZhQANdCPjuYlPO8asuhWQynZq0vM7DoOxhYjIUhpVoPFhgh9Pc&s=1',
      can_boost_post: boolean,
      can_see_organic_insights: boolean,
      show_insights_terms: boolean,
      can_convert_to_business: boolean,
      can_create_sponsor_tags: boolean,
      is_allowed_to_create_standalone_nonprofit_fundraisers: boolean,
      is_allowed_to_create_standalone_personal_fundraisers: boolean,
      can_create_new_standalone_fundraiser: boolean,
      can_create_new_standalone_personal_fundraiser: boolean,
      can_be_tagged_as_sponsor: boolean,
      can_see_support_inbox: boolean,
      can_see_support_inbox_v1: boolean,
      total_igtv_videos: number,
      has_igtv_series: boolean,
      total_clips_count: number,
      has_saved_items: boolean,
      total_ar_effects: number,
      reel_auto_archive: string,
      is_profile_action_needed: boolean,
      usertags_count: number,
      usertag_review_enabled: boolean,
      is_needy: boolean,
      is_interest_account: boolean,
      has_chaining: boolean,
      hd_profile_pic_url_info: {
        url:
          'https://scontent-lhr8-1.cdninstagram.com/v/t51.2885-19/82155853_495819618006168_2122337653864005632_n.jpg?_nc_ht=scontent-lhr8-1.cdninstagram.com&_nc_ohc=a825I9qCm68AX_rao5-&ccb=7-4&oh=0910484a144588424948be17650be508&oe=608B1AC3&_nc_sid=a9513d',
        width: number,
        height: number,
      },
      has_placed_orders: boolean,
      can_tag_products_from_merchants: boolean,
      fbpay_experience_enabled: boolean,
      show_conversion_edit_entry: boolean,
      aggregate_promote_engagement: boolean,
      allowed_commenter_type: string,
      is_video_creator: boolean,
      has_profile_video_feed: boolean,
      has_highlight_reels: boolean,
      has_guides: boolean,
      is_eligible_to_show_fb_cross_sharing_nux: boolean,
      page_id_for_new_suma_biz_account: null,
      eligible_shopping_signup_entrypoints: any,
      service_shop_onboarding_status: null,
      service_shop_merchant_entrypoint_app_id:
        string,
      can_be_reported_as_fraud: boolean,
      is_business: boolean,
      account_type: 1,
      professional_conversion_suggested_account_type: 2,
      is_call_to_action_enabled: null,
      interop_messaging_user_fbid: number,
      linked_fb_info: {
        linked_fb_user: {
          id: number,
          name: string,
          is_valid: boolean,
        },
      },
      standalone_fundraiser_info: {
        has_active_fundraiser: boolean,
        fundraiser_id: null,
        fundraiser_title: null,
        fundraiser_type: null,
        formatted_goal_amount: null,
        beneficiary_username: null,
        formatted_fundraiser_progress_info_text: null,
        percent_raised: null,
      },
      allow_mention_setting: string,
      allow_tag_setting: string,
      can_see_primary_country_in_settings: boolean,
      personal_account_ads_page_name: string,
      personal_account_ads_page_id: string,
      account_badges: Array<any>,
      whatsapp_number: string,
      has_eligible_whatsapp_linking_category: null,
      fbid_v2: number,
      is_eligible_for_appointment_creation_in_direct_thread: boolean,
      include_direct_blacklist_status: boolean,
      can_follow_hashtag: boolean,
      is_potential_business: boolean,
      show_post_insights_entry_point: boolean,
      feed_post_reshare_disabled: boolean,
      besties_count: number,
      show_besties_badge: boolean,
      recently_bestied_by_count: number,
      nametag: {
        mode: number,
        gradient: number,
        emoji: string,
        selfie_sticker:number,
      },
      existing_user_age_collection_enabled: boolean,
      about_your_account_bloks_entrypoint_enabled: boolean,
      auto_expand_chaining: boolean,
      highlight_reshare_disabled: boolean,
      is_memorialized: boolean,
      open_external_url_with_in_app_browser: boolean,
    },
    status: string,
  


}//END_CLASS
